# Site settings
title: AEL Computer Science
email: ael-intro-cs-2015-2016@googlegroups.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aelcs.link" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
